box:
  developer-token: DO9oXU7YG8GsJ0nluzU4N2RViWoGDzSW
  client-id: 7c65kcitmjn6krqyuqo9wux5ri1m3bhw
  client-secret: socZxWxkMe4AgNVwDjFlwk26UISJAuXm
  enterprise-id: "0"
  public-key-id: plb4l7d0
  private-key: |
    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIIFLTBXBgkqhkiG9w0BBQ0wSjApBgkqhkiG9w0BBQwwHAQIMDBEXCE1h+4CAggA
    MAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBDu4mS5A7yMqRDFNJw4d0XDBIIE
    0Md8rR62iP2QqLwXIDDkb26JO1Z0RxVdrfiJGmLkUByByJ9gp7LTnwEgSsEwcfK+
    q5ZZDiMEdPNO/Bi0ujDeYHy7Sy5yAIb/3W+ymCE9vx31XLLmuOeMuzEp+/eexcrD
    DF+pV2bFeJQDlQKF1IyA2PXZxCxVe3aWpzjzXhuG2phQcJcdvwueuuJl8GxZs7zF
    IibpvzrfXyjfUx1SInSkdXUocwpEbF1/2jKLNKGu1Kweu2YNeq0s5FYoxu+OCmYf
    Ap0nFILJSPLpMGnJARrWl9ElRaofzbwxHFbst3Gab+elCJAoJT47bgHbCT8fd8ce
    zZD8xprC8diUutaoV2Pl44MYcqcPfYTp0a2PyG9OKQmK45/1CyHapkgxYwhEHuj0
    JIr7nqg4atdcE2BOqvnwwQt3Ve63MUCXkHP63ET3OkJWUDbBUyrGtQ1HhHdqBKyB
    qUuUE17w7j0J8i0kvw64FcYwaclWDtLr7ap67Qx7gSFX+9K73Yrw26Gn9nKSi+ZS
    Tv+1h7vYeMkk+tTi4DDMTyHvHPMXIakzsKfIYgJMq1QXksAr2qqC7AZJYFh4AcT4
    DciILmhWZYPk8NPqrYZYTut3jnFkYnIPxLnvwIqt/de4AdrsYDOlur1izM1leTex
    DiukJkPPze/whk8VLP4pNnk4ZzDV7/DkQAxQT0HLkB+GL/NUPVI/UOME6q0BU6GS
    uKFvgWihY4oZ73dTckW4MfSikoX352mt1brIM4emP0Vu+2rh2AIsrtT9YxrN+nJk
    byO40xnj5v1uMchPYGikJ//zywyud2FDUPy3hXAjy5XkGhSFqbPSxVUVdI+75sRn
    eXFLcMPINvRwjodRtT81OcnGX/VjKrpUxlSFpHlAxrOB0fFYUNytQbSg4/tOSJte
    rmsS3EsLzsrt6k6fA53uN8AKzwm8azHOQj2D3CQ+aXRPgZmyV8WPMYsWlVk5JypS
    1iFiXaX+O7fcB5JleFypbyWBXc9Xmg66uXk2c6A+GlaACvU4D0RRc7iJ5feBgG0x
    leIyUExgQxODGk25CT8f8iYzkDh8VZHTTSNPHjk/wEU4VQ70SFQwDNKDs2MbpH2t
    bQdAYnviK9nmvX85mlA4g07HzzRhRXeMY+Th4CRSrBvJut68/yzwhoWbysveV9zH
    Qv24cRJIHl0AfiXQLcjpipvhmzzidUBg2CuaumagMmx5q5obEuOK9OSxafDlFO4j
    FI0h05k3rI+8kMzXUCI75E2311DrDHhE2ujqCMM0AcAyTdnLyqXu1KjjBMS0cw4G
    lX3aZJC3epGa856+24jiyriGanQP0lkmr1ToxnjwquGyB7JKffvXj5sW5ZST5sbC
    b9Qct9vtnaunkbNp5ED0wwxeyjOSxvh3EGq0190ZbBgn7HN3UMWFdkYc2aXU3j8Y
    op8mBTgO5PIkRa+WnC1Pr9DD1ToYoW4pQzlqdnkOa/lRnQL/Juk7q36z6NPMP+XP
    ku2ZKreFrxmw8HIe6mbcNLDVstSZXSSBi8ETpa5sJJRThuJ248ZVU4bEzpfsU8Ux
    vDkyuxo5ezaSvMV2oUyFPqc6hWCdjeulabSIuU4IBhPZxfQORd/I0r/GqjApb0eh
    oBBL1PPJxFIhBfIa5Mp5bq3R/mefr+PAKge1MxFfDgVL
    -----END ENCRYPTED PRIVATE KEY-----
  private-key-password: 25782da7ed3dcc3ca4ffe8433a98b02e
  webhook-folder-id: 333896344372
  webhook-address:  https://a766afb95762.ngrok-free.app/webhook

malwarebazaar:
  api-key: 7ca551097b1748eff3c73c3da3e799ac028dd5cf8650b328
  base-url: https://mb-api.abuse.ch/api/v1/

